// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: src/pb/common.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EInvoicePartner int32

const (
	EInvoicePartner_MISA    EInvoicePartner = 0
	EInvoicePartner_VIETTEL EInvoicePartner = 1
	EInvoicePartner_VNPT    EInvoicePartner = 2
)

// Enum value maps for EInvoicePartner.
var (
	EInvoicePartner_name = map[int32]string{
		0: "MISA",
		1: "VIETTEL",
		2: "VNPT",
	}
	EInvoicePartner_value = map[string]int32{
		"MISA":    0,
		"VIETTEL": 1,
		"VNPT":    2,
	}
)

func (x EInvoicePartner) Enum() *EInvoicePartner {
	p := new(EInvoicePartner)
	*p = x
	return p
}

func (x EInvoicePartner) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EInvoicePartner) Descriptor() protoreflect.EnumDescriptor {
	return file_src_pb_common_proto_enumTypes[0].Descriptor()
}

func (EInvoicePartner) Type() protoreflect.EnumType {
	return &file_src_pb_common_proto_enumTypes[0]
}

func (x EInvoicePartner) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EInvoicePartner.Descriptor instead.
func (EInvoicePartner) EnumDescriptor() ([]byte, []int) {
	return file_src_pb_common_proto_rawDescGZIP(), []int{0}
}

type KVSoftware int32

const (
	KVSoftware_RETAIL  KVSoftware = 0
	KVSoftware_FNB     KVSoftware = 1
	KVSoftware_BOOKING KVSoftware = 2
)

// Enum value maps for KVSoftware.
var (
	KVSoftware_name = map[int32]string{
		0: "RETAIL",
		1: "FNB",
		2: "BOOKING",
	}
	KVSoftware_value = map[string]int32{
		"RETAIL":  0,
		"FNB":     1,
		"BOOKING": 2,
	}
)

func (x KVSoftware) Enum() *KVSoftware {
	p := new(KVSoftware)
	*p = x
	return p
}

func (x KVSoftware) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KVSoftware) Descriptor() protoreflect.EnumDescriptor {
	return file_src_pb_common_proto_enumTypes[1].Descriptor()
}

func (KVSoftware) Type() protoreflect.EnumType {
	return &file_src_pb_common_proto_enumTypes[1]
}

func (x KVSoftware) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KVSoftware.Descriptor instead.
func (KVSoftware) EnumDescriptor() ([]byte, []int) {
	return file_src_pb_common_proto_rawDescGZIP(), []int{1}
}

type Merchant struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MerchantId   int64      `protobuf:"varint,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	MerchantCode KVSoftware `protobuf:"varint,2,opt,name=merchant_code,json=merchantCode,proto3,enum=main.KVSoftware" json:"merchant_code,omitempty"`
}

func (x *Merchant) Reset() {
	*x = Merchant{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_pb_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Merchant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Merchant) ProtoMessage() {}

func (x *Merchant) ProtoReflect() protoreflect.Message {
	mi := &file_src_pb_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Merchant.ProtoReflect.Descriptor instead.
func (*Merchant) Descriptor() ([]byte, []int) {
	return file_src_pb_common_proto_rawDescGZIP(), []int{0}
}

func (x *Merchant) GetMerchantId() int64 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *Merchant) GetMerchantCode() KVSoftware {
	if x != nil {
		return x.MerchantCode
	}
	return KVSoftware_RETAIL
}

type Page struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page  int32 `protobuf:"varint,1,opt,name=Page,proto3" json:"Page,omitempty"`
	Limit int32 `protobuf:"varint,2,opt,name=Limit,proto3" json:"Limit,omitempty"`
}

func (x *Page) Reset() {
	*x = Page{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_pb_common_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Page) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Page) ProtoMessage() {}

func (x *Page) ProtoReflect() protoreflect.Message {
	mi := &file_src_pb_common_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Page.ProtoReflect.Descriptor instead.
func (*Page) Descriptor() ([]byte, []int) {
	return file_src_pb_common_proto_rawDescGZIP(), []int{1}
}

func (x *Page) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *Page) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

var File_src_pb_common_proto protoreflect.FileDescriptor

var file_src_pb_common_proto_rawDesc = []byte{
	0x0a, 0x13, 0x73, 0x72, 0x63, 0x2f, 0x70, 0x62, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x61, 0x69, 0x6e, 0x22, 0x62, 0x0a, 0x08, 0x4d,
	0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x65, 0x72, 0x63, 0x68,
	0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x6d, 0x65,
	0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x35, 0x0a, 0x0d, 0x6d, 0x65, 0x72, 0x63,
	0x68, 0x61, 0x6e, 0x74, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x10, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x4b, 0x56, 0x53, 0x6f, 0x66, 0x74, 0x77, 0x61, 0x72,
	0x65, 0x52, 0x0c, 0x6d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x22,
	0x30, 0x0a, 0x04, 0x50, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x50, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x4c,
	0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x4c, 0x69, 0x6d, 0x69,
	0x74, 0x2a, 0x32, 0x0a, 0x0f, 0x45, 0x49, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x50, 0x61, 0x72,
	0x74, 0x6e, 0x65, 0x72, 0x12, 0x08, 0x0a, 0x04, 0x4d, 0x49, 0x53, 0x41, 0x10, 0x00, 0x12, 0x0b,
	0x0a, 0x07, 0x56, 0x49, 0x45, 0x54, 0x54, 0x45, 0x4c, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x56,
	0x4e, 0x50, 0x54, 0x10, 0x02, 0x2a, 0x2e, 0x0a, 0x0a, 0x4b, 0x56, 0x53, 0x6f, 0x66, 0x74, 0x77,
	0x61, 0x72, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x52, 0x45, 0x54, 0x41, 0x49, 0x4c, 0x10, 0x00, 0x12,
	0x07, 0x0a, 0x03, 0x46, 0x4e, 0x42, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x42, 0x4f, 0x4f, 0x4b,
	0x49, 0x4e, 0x47, 0x10, 0x02, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_src_pb_common_proto_rawDescOnce sync.Once
	file_src_pb_common_proto_rawDescData = file_src_pb_common_proto_rawDesc
)

func file_src_pb_common_proto_rawDescGZIP() []byte {
	file_src_pb_common_proto_rawDescOnce.Do(func() {
		file_src_pb_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_src_pb_common_proto_rawDescData)
	})
	return file_src_pb_common_proto_rawDescData
}

var file_src_pb_common_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_src_pb_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_src_pb_common_proto_goTypes = []interface{}{
	(EInvoicePartner)(0), // 0: main.EInvoicePartner
	(KVSoftware)(0),      // 1: main.KVSoftware
	(*Merchant)(nil),     // 2: main.Merchant
	(*Page)(nil),         // 3: main.Page
}
var file_src_pb_common_proto_depIdxs = []int32{
	1, // 0: main.Merchant.merchant_code:type_name -> main.KVSoftware
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_src_pb_common_proto_init() }
func file_src_pb_common_proto_init() {
	if File_src_pb_common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_src_pb_common_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Merchant); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_pb_common_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Page); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_src_pb_common_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_src_pb_common_proto_goTypes,
		DependencyIndexes: file_src_pb_common_proto_depIdxs,
		EnumInfos:         file_src_pb_common_proto_enumTypes,
		MessageInfos:      file_src_pb_common_proto_msgTypes,
	}.Build()
	File_src_pb_common_proto = out.File
	file_src_pb_common_proto_rawDesc = nil
	file_src_pb_common_proto_goTypes = nil
	file_src_pb_common_proto_depIdxs = nil
}
